#ifndef ENUM_HPP
#define ENUM_HPP
#include<string>

extern int PRIORITY[];

extern std::string OPERTEXT[31];

enum OPERATOR {
	LBRACKET, RBRACKET,
	COMMA,
	FUNCTION, RETURN, ENDFUNCTION,
	IF, ELSE,
	WHILE, ENDLOOP,
	GOTO, ASSIGN, COLON,
	OR,
	AND,
	BITOR,
	XOR,
	BITAND,
	EQ, NEQ,
	SHL, SHR,
	LEQ, LT,
	GEQ, GT,
	PLUS, MINUS,
	MULT, DIV, MOD
};

enum ERRORS {
	ERR_UNDEFINED_OPERATOR,
	ERR_WITH_GOTO_OR_LABELS,
	ERR_NOT_BALANCED_BRACKETS,
	ERR_NOT_BALANCED_FUNCTION,
	ERR_NOT_BALANCED_CONDITIONAL_OPERATORS,
	ERR_NAME_FUNCTION,
	ERR_FUNCTION_START_VARS,
	ERR_WITH_CONDITIONAL_OPERATORS,
	ERR_UNDEFINED_MAIN,
	ERR_UNDEFINED_VARIABLE,
	ERR_UNDEFINED_FUNCTION,
	ERR_ASSIGN_PROBLEMS,
	ERR_NO_COLONS_IN_CONDITION,
	ERR_WRONG_POSITION_FUNCTION,
	INVALID_SYNTAX,
	ERR_VOID_FUNCTION_IN_EVALUATION,
	ERR_DIVISION_BY_ZERO
};

enum {UNDEFINED = -INT32_MAX};

enum {FUNCTION_RETURN = -1};

#endif